[api]
url = "http://localhost:8001"
timeout = 30

[auth]
auto_login = true
remember_token = true

[output]
colors = true
pager = "auto"
max_results = 20

[cache]
enabled = true
max_size_mb = 100
sync_interval = 300
